# Generated by Django 3.1.7 on 2021-03-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_apiusers_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiUsers',
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
